<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\ProjectJA.SharedKernel\ProjectJA.SharedKernel.csproj" />
    <ProjectReference Include="..\ProjectJA.Modules.Identity\ProjectJA.Modules.Identity.csproj" />
    <ProjectReference Include="..\ProjectJA.Modules.Projects\ProjectJA.Modules.Projects.csproj" />
    <ProjectReference Include="..\ProjectJA.Modules.Issues\ProjectJA.Modules.Issues.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
